package io.github.protasm.jvmud.runtime;

/** Native JVMud lifecycle moments that a mudlib may map to its own methods. */
public enum MudlibLifecycleEvent {
    OBJECT_LOADED,
    OBJECT_ACTIVATED,
    OBJECT_DESTRUCTION_REQUESTED,
    OBJECT_DESTROYED,
    ENTITY_ARRIVED_AT_PLACE,
    ENTITY_DEPARTED_FROM_PLACE,
    ENTITY_ADDED_TO_ENTITY,
    ENTITY_REMOVED_FROM_ENTITY,
    PLAYER_SESSION_CONNECTED,
    PLAYER_PERSONA_RESOLVED,
    PLAYER_OBJECT_BOUND,
    PLAYER_ENTERED_WORLD,
    PLAYER_SESSION_DISCONNECTED,
    INTERACTION_SCOPE_STARTED,
    COMMAND_DISPATCH_STARTED,
    COMMAND_DISPATCH_FINISHED,
    LOG_ERROR,
    RUNTIME_ERROR,
    SCHEDULED_TICK_ERROR,
    SERVER_SHUTDOWN,
    SCHEDULED_TICK,
    DEFERRED_CALLBACK
}
