/**
 * Compiled-LPC support runtime consumed by generated bytecode.
 *
 * <p>Provides the active generated-code context, truthiness utilities aligned with LPC semantics,
 * and a runtime type model that captures JVM descriptors for IR and code generation.</p>
 *
 * <p>This package is not the JVMud engine ontology. Engine-owned world concepts such as players,
 * sessions, personas, places, entities, scheduling, and mudlib boundaries live under {@code
 * io.github.protasm.jvmud.engine}; compiler and LPC compatibility layers adapt into that model.</p>
 */
package io.github.protasm.jvmud.compiler.runtime;
