/**
 * LPC-facing engine function contracts.
 *
 * <p>An efun is a Java implementation of an LPC-callable engine operation. Mudlib code calls the
 * function by name; semantic analysis checks the call against an {@link
 * io.github.protasm.jvmud.compiler.efun.EfunSignature}; generated bytecode resolves the function
 * through the active {@link io.github.protasm.jvmud.compiler.runtime.RuntimeContext}; and the
 * resolved {@link io.github.protasm.jvmud.compiler.efun.Efun} performs the operation against the
 * current runtime state.</p>
 *
 * <p>This package contains only the small contract surface:</p>
 * <ul>
 *   <li>{@link io.github.protasm.jvmud.compiler.efun.Efun} is the executable function body plus
 *       signature.</li>
 *   <li>{@link io.github.protasm.jvmud.compiler.efun.EfunSignature} records the LPC-facing name,
 *       return type, and parameter types for one overload.</li>
 *   <li>{@link io.github.protasm.jvmud.compiler.efun.EfunRegistry} stores runtime-scoped efun
 *       implementations and resolves them by name and exact arity.</li>
 * </ul>
 *
 * <p>The built-in JVMud efuns are defined in {@link
 * io.github.protasm.jvmud.compiler.efun.builtin.CoreEfuns}. Compatibility mudlibs can expose familiar
 * LPC driver names by wrapping or delegating to those JVMud-native operations, while keeping the
 * engine-facing contract centered on entities, command dispatch, scheduling, persistence, session
 * input, and host integration.</p>
 */
package io.github.protasm.jvmud.compiler.efun;
