package io.github.protasm.lpc2j.parser.type;

public enum InstrType {
    IT_BINARY, IT_CONST_FLOAT, IT_CONST_INT, IT_CONST_STR, IT_FIELD_LOAD, IT_FIELD_STORE, IT_I2F, IT_INVOKE,
    IT_INVOKE_OTHER, IT_LITERAL, IT_LOC_LOAD, IT_LOC_STORE, IT_NEGATE, IT_POP, IT_RETURN, IT_RETURNVAL, IT_LOAD_THIS,
    IT_NEW_ARRAY;
}
