package io.github.protasm.jvmud.compiler.efun;

import io.github.protasm.jvmud.compiler.parser.ast.Symbol;
import io.github.protasm.jvmud.compiler.parser.type.LPCType;
import java.util.List;
import java.util.Objects;

/**
 * Describes the LPC-facing signature of an engine function.
 *
 * <p>The {@link Symbol} stores the function name and return type. The parameter list stores the
 * LPC types accepted by one concrete overload. JVMud overloads efuns by arity, so two signatures may
 * share a name when their parameter counts differ.</p>
 *
 * @param symbol function symbol containing the LPC-facing name and return type
 * @param parameterTypes LPC parameter types for this overload
 */
public record EfunSignature(Symbol symbol, List<LPCType> parameterTypes) {
    /**
     * Creates an immutable signature.
     *
     * <p>A {@code null} parameter list is normalized to an empty list so zero-argument efuns can be
     * declared tersely by simple callers.</p>
     */
    public EfunSignature {
        Objects.requireNonNull(symbol, "symbol");
        parameterTypes = List.copyOf(parameterTypes != null ? parameterTypes : List.of());
    }

    /**
     * Returns the LPC-facing function name.
     *
     * @return function name used in LPC calls and registry lookup
     */
    public String name() {
        return symbol.name();
    }

    /**
     * Returns the LPC return type.
     *
     * @return return type advertised to semantic analysis and generated bytecode
     */
    public LPCType returnType() {
        return symbol.lpcType();
    }

    /**
     * Returns the exact number of LPC arguments accepted by this overload.
     *
     * @return parameter count
     */
    public int arity() {
        return parameterTypes.size();
    }
}
