package io.github.protasm.jvmud.compiler.efun;

import io.github.protasm.jvmud.compiler.runtime.RuntimeContext;
import io.github.protasm.jvmud.compiler.parser.ast.Symbol;

/**
 * Runtime implementation of one LPC-facing engine function.
 *
 * <p>An efun is a small Java adapter behind an LPC-callable function name. The compiler sees its
 * {@link EfunSignature}; generated bytecode resolves that signature by name and arity through a
 * {@link RuntimeContext}; and the implementation receives already-evaluated LPC argument values as
 * ordinary Java objects.</p>
 *
 * <p>Efuns should keep their surface area engine-facing and stable. Mudlib compatibility layers may
 * expose traditional driver names, but those names should delegate into these implementations rather
 * than redefine engine concepts. The runtime context supplies the execution state an efun normally
 * needs: current object, previous object, command Persona, output/session sinks, object loading,
 * containment, scheduling, persistence, and host integration.</p>
 *
 * <p>Implementations are looked up by exact arity. If an efun supports several argument counts,
 * register one {@code Efun} instance per supported arity.</p>
 */
public interface Efun {
    /**
     * Returns the function signature exposed to the compiler and runtime lookup tables.
     *
     * <p>The signature's symbol contains both the LPC-facing name and the return type. Its
     * parameter list is used for compile-time checking and runtime arity lookup.</p>
     *
     * @return LPC-facing function signature
     */
    EfunSignature signature();

    /**
     * Executes the function body.
     *
     * <p>Callers should normally use {@link #invoke(RuntimeContext, Object[])} so arity checking
     * stays consistent. Implementations may assume the argument array length matches
     * {@link #arity()}.</p>
     *
     * @param context active runtime context for the LPC execution
     * @param args evaluated LPC argument values
     * @return LPC result value, or {@code null} for void efuns
     */
    Object call(RuntimeContext context, Object[] args);

    /**
     * Returns the compiler symbol associated with this function.
     *
     * @return signature symbol containing the LPC name and return type
     */
    default Symbol symbol() {
        return signature().symbol();
    }

    /**
     * Returns the number of LPC arguments this implementation accepts.
     *
     * @return exact arity used for registry lookup and invocation checks
     */
    default int arity() {
        return signature().arity();
    }

    /**
     * Checks arity and invokes this function.
     *
     * <p>A {@code null} argument array is treated as zero arguments. Argument values are not
     * coerced here; semantic analysis and generated bytecode are responsible for type-compatible
     * calls before the efun is invoked.</p>
     *
     * @param context active runtime context for the LPC execution
     * @param args evaluated LPC argument values, or {@code null} for no arguments
     * @return LPC result value, or {@code null} for void efuns
     * @throws IllegalArgumentException if the supplied argument count differs from the signature
     */
    default Object invoke(RuntimeContext context, Object[] args) {
        Object[] a = (args == null) ? new Object[0] : args;

        if (a.length != arity())
            throw new IllegalArgumentException(
                    "engine function '" + symbol().name() + "' expects " + arity() + " arg(s); got " + a.length);

        return call(context, a);
    }
}
