/**
 * Interfaces and registry for LPC efuns: engine functions callable from mudlib code.
 *
 * <p>Defines the {@link io.github.protasm.jvmud.compiler.efun.Efun} contract, the {@link
 * io.github.protasm.jvmud.compiler.efun.EfunSignature} metadata, and an instance-scoped {@link
 * io.github.protasm.jvmud.compiler.efun.EfunRegistry} for lookups at runtime. Engine functions provide names, typed
 * signatures, and invocation behavior used by generated bytecode.</p>
 *
 * <p>Assumes concrete implementations are supplied elsewhere (e.g., console engine functions) and registered
 * with a {@link io.github.protasm.jvmud.compiler.runtime.RuntimeContext} before compiled code executes. The
 * registry enforces arity and rejects ambiguous overloads.</p>
 */
package io.github.protasm.jvmud.compiler.efun;
