package io.github.protasm.jvmud.compiler.exec;

import io.github.protasm.jvmud.compiler.efun.Efun;
import io.github.protasm.jvmud.compiler.parser.ast.ASTObject;
import io.github.protasm.jvmud.compiler.pipeline.CompilationPipeline;
import io.github.protasm.jvmud.compiler.pipeline.CompilationProblem;
import io.github.protasm.jvmud.compiler.pipeline.CompilationResult;
import io.github.protasm.jvmud.compiler.pipeline.CompilationUnit;
import io.github.protasm.jvmud.compiler.parser.ParserOptions;
import io.github.protasm.jvmud.compiler.runtime.RuntimeContext;
import io.github.protasm.jvmud.compiler.runtime.RuntimeContextHolder;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Host-facing LPC execution runtime that owns classloading, object identity, and runtime context.
 *
 * <p>This runtime is distinct from {@code io.github.protasm.jvmud.compiler.runtime}, which contains the
 * language-level helpers used by generated bytecode. {@code LpcRuntime} sits above the compiler
 * pipeline and provides a minimal API for loading LPC objects from source code.</p>
 *
 * <p>Usage example:</p>
 *
 * <pre>{@code
 * LpcRuntime runtime = new LpcRuntime(LpcRuntimeConfig.builder()
 *         .baseIncludePath(Path.of("mudlib"))
 *         .build());
 * LpcObjectHandle orc = runtime.load("/obj/orc.c");
 * runtime.withRuntimeContext(() -> {
 *     orc.instance().getClass().getMethod("init").invoke(orc.instance());
 *     return null;
 * });
 * }</pre>
 */
public final class LpcRuntime {
    private LpcRuntimeClassLoader classLoader;
    private final RuntimeContext runtimeContext;
    private final CompilationPipeline pipeline;
    private final Path baseIncludePath;

    public LpcRuntime(LpcRuntimeConfig config) {
        Objects.requireNonNull(config, "config");
        this.baseIncludePath = config.baseIncludePath();
        this.runtimeContext = new RuntimeContext(config.resolveIncludeResolver());
        this.runtimeContext.setObjectFactory(this::cloneObject);
        this.classLoader = new LpcRuntimeClassLoader(config.parentClassLoader());
        this.pipeline = new CompilationPipeline(config.parentInternalName(), runtimeContext, config.compilationObserver());
    }

    public LpcObjectHandle load(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        return load(resolveSourcePathWithExtensions(sourcePath));
    }

    public Object loadOrGetObject(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String internalName = normalizeInternalName(deriveSourceName(normalized, baseIncludePath));
        Object existing = runtimeContext.getObject(internalName);
        if (existing != null) {
            return existing;
        }
        return load(normalized).instance();
    }

    public LpcObjectHandle reload(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        return reload(resolveSourcePathWithExtensions(sourcePath));
    }

    public LpcObjectHandle reload(Path sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String internalName = normalizeInternalName(deriveSourceName(normalized, baseIncludePath));
        Object existing = runtimeContext.getObject(internalName);
        if (existing != null) {
            runtimeContext.destructObject(existing);
        }

        // JVM classes cannot be redefined in the same classloader. A fresh loader lets the
        // reloaded LPC source produce a new generated class while old live objects keep working.
        classLoader = new LpcRuntimeClassLoader(classLoader.getParent());
        return load(normalized);
    }

    public LpcObjectHandle load(Path sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String source;

        try {
            if (!Files.exists(normalized)) {
                throw new LpcRuntimeException("Source file not found: " + normalized);
            }
            source = Files.readString(normalized);
        } catch (IOException e) {
            throw new LpcRuntimeException("Failed to read source file: " + normalized, e);
        }

        String sourceName = deriveSourceName(normalized, baseIncludePath);
        String displayPath = "/" + sourceName;
        CompilationResult result =
                pipeline.run(normalized, source, sourceName, displayPath, ParserOptions.defaults());

        if (!result.getProblems().isEmpty()) {
            throw new LpcRuntimeException(formatProblems(result.getProblems()), result.getProblems());
        }

        CompilationUnit compilationUnit = result.getCompilationUnit();
        if (compilationUnit != null) {
            defineInheritedClasses(compilationUnit.parentUnit());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LpcRuntimeException("Compilation did not produce bytecode for " + sourceName);
        }

        String internalName = (result.getAstObject() != null) ? result.getAstObject().name() : sourceName;
        internalName = normalizeInternalName(internalName);
        Class<?> compiledClass = classLoader.defineClass(internalName, bytecode);
        Object instance = instantiate(compiledClass);

        registerObject(internalName, instance);
        resetIfPresent(instance);

        return new LpcObjectHandle(this, internalName, compiledClass, instance);
    }

    public LpcLoadResult tryLoad(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        try {
            return LpcLoadResult.success(load(sourcePath));
        } catch (RuntimeException e) {
            return LpcLoadResult.failure(e);
        }
    }

    public LpcLoadResult tryLoad(Path sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        try {
            return LpcLoadResult.success(load(sourcePath));
        } catch (RuntimeException e) {
            return LpcLoadResult.failure(e);
        }
    }

    public LpcObjectHandle loadSource(String sourceName, String source) {
        Objects.requireNonNull(sourceName, "sourceName");
        Objects.requireNonNull(source, "source");
        String normalizedName = normalizeInternalName(stripExtension(sourceName));
        String displayPath = "/" + normalizedName;

        CompilationResult result =
                pipeline.run(null, source, normalizedName, displayPath, ParserOptions.defaults());

        if (!result.getProblems().isEmpty()) {
            throw new LpcRuntimeException(formatProblems(result.getProblems()), result.getProblems());
        }

        CompilationUnit compilationUnit = result.getCompilationUnit();
        if (compilationUnit != null) {
            defineInheritedClasses(compilationUnit.parentUnit());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LpcRuntimeException("Compilation did not produce bytecode for " + normalizedName);
        }

        String internalName = (result.getAstObject() != null) ? result.getAstObject().name() : normalizedName;
        internalName = normalizeInternalName(internalName);
        Class<?> compiledClass = classLoader.defineClass(internalName, bytecode);
        Object instance = instantiate(compiledClass);

        registerObject(internalName, instance);
        resetIfPresent(instance);

        return new LpcObjectHandle(this, internalName, compiledClass, instance);
    }

    public Object cloneObject(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String internalName = deriveSourceName(normalized, baseIncludePath);
        internalName = normalizeInternalName(internalName);

        Class<?> objectClass = ensureClassDefined(normalized, internalName);
        Object instance = instantiate(objectClass);
        registerObject(nextCloneId(internalName), instance);
        resetIfPresent(instance);
        return instance;
    }

    public void moveObject(Object object, Object destination) {
        runtimeContext.moveObject(object, destination);
    }

    public Object environment(Object object) {
        return runtimeContext.environment(object);
    }

    public Object present(Object identifier, Object container) {
        return runtimeContext.present(identifier, container);
    }

    public Object firstInventory(Object container) {
        return runtimeContext.firstInventory(container);
    }

    public Object nextInventory(Object object) {
        return runtimeContext.nextInventory(object);
    }

    public void destructObject(Object object) {
        runtimeContext.destructObject(object);
    }

    public void registerHostObject(String objectId, Object object) {
        runtimeContext.registerObject(normalizeInternalName(objectId), object);
    }

    public Object invokeObject(Object object, String methodName, Object... args) {
        return withRuntimeContext(() -> runtimeContext.invokeObject(object, methodName, args));
    }

    public void refreshCommandActions(Object actor) {
        Objects.requireNonNull(actor, "actor");
        withRuntimeContext(() -> runtimeContext.withCommandActor(actor, () -> {
            runtimeContext.clearCommandActions(actor);
            runtimeContext.clearPendingActionMethods();
            try {
                initializeIfPresent(actor);
                Object environment = runtimeContext.environment(actor);
                if (environment != null) {
                    initializeIfPresent(environment);
                    forEachInventory(environment, this::initializeIfPresent);
                }
                forEachInventory(actor, this::initializeIfPresent);
            } finally {
                runtimeContext.clearPendingActionMethods();
            }
            return null;
        }));
    }

    public Object dispatchCommand(Object actor, String commandLine) {
        Objects.requireNonNull(actor, "actor");
        Objects.requireNonNull(commandLine, "commandLine");
        return withRuntimeContext(() -> runtimeContext.withCommandActor(actor, () ->
                runtimeContext.dispatchCommand(actor, commandLine)));
    }

    public LpcObjectInspection inspectObject(Object object) {
        Objects.requireNonNull(object, "object");
        Object environment = runtimeContext.environment(object);
        List<String> inventoryIds = new ArrayList<>();
        Object child = runtimeContext.firstInventory(object);
        while (child != null) {
            inventoryIds.add(objectReference(child));
            child = runtimeContext.nextInventory(child);
        }

        return new LpcObjectInspection(
                runtimeContext.objectId(object),
                object.getClass().getName(),
                environment == null ? null : objectReference(environment),
                inventoryIds,
                inspectFields(object),
                inspectMethods(object));
    }

    public void registerEfun(Efun efun) {
        runtimeContext.registerEfun(efun);
    }

    public void setOutputSink(Consumer<String> outputSink) {
        runtimeContext.setOutputSink(outputSink);
    }

    public String outputTranscript() {
        return runtimeContext.outputTranscript();
    }

    public void clearOutputTranscript() {
        runtimeContext.clearOutputTranscript();
    }

    public <T> T withRuntimeContext(Supplier<T> action) {
        Objects.requireNonNull(action, "action");
        RuntimeContext previous = RuntimeContextHolder.current();
        RuntimeContextHolder.setCurrent(runtimeContext);
        try {
            return action.get();
        } finally {
            RuntimeContextHolder.setCurrent(previous);
        }
    }

    public <T> T withCurrentObject(Object object, Supplier<T> action) {
        Objects.requireNonNull(action, "action");
        return withRuntimeContext(() -> runtimeContext.withCurrentObject(object, action));
    }

    public void runWithCurrentObject(Object object, Runnable action) {
        Objects.requireNonNull(action, "action");
        withCurrentObject(object, () -> {
            action.run();
            return null;
        });
    }

    public void runWithRuntimeContext(Runnable action) {
        Objects.requireNonNull(action, "action");
        withRuntimeContext(() -> {
            action.run();
            return null;
        });
    }

    private Object instantiate(Class<?> compiledClass) {
        return withRuntimeContext(() -> {
            try {
                return compiledClass.getDeclaredConstructor().newInstance();
            } catch (InstantiationException
                    | IllegalAccessException
                    | InvocationTargetException
                    | NoSuchMethodException e) {
                throw new LpcRuntimeException("Failed to instantiate LPC object: " + compiledClass.getName(), e);
            }
        });
    }

    private void forEachInventory(Object container, Consumer<Object> action) {
        Object child = runtimeContext.firstInventory(container);
        while (child != null) {
            Object next = runtimeContext.nextInventory(child);
            action.accept(child);
            child = next;
        }
    }

    private void initializeIfPresent(Object object) {
        try {
            object.getClass().getMethod("init");
        } catch (NoSuchMethodException ignored) {
            // Objects are not required to define init().
            return;
        }

        runtimeContext.invokeObject(object, "init");
    }

    private void resetIfPresent(Object object) {
        try {
            object.getClass().getMethod("reset", Object.class);
        } catch (NoSuchMethodException ignored) {
            return;
        }

        withRuntimeContext(() -> runtimeContext.invokeObject(object, "reset", 0));
    }

    private List<LpcObjectInspection.FieldValue> inspectFields(Object object) {
        List<LpcObjectInspection.FieldValue> fields = new ArrayList<>();
        Class<?> type = object.getClass();
        while (type != null && type != Object.class) {
            for (Field field : type.getDeclaredFields()) {
                if (field.isSynthetic()) {
                    continue;
                }
                try {
                    field.setAccessible(true);
                    fields.add(new LpcObjectInspection.FieldValue(
                            type.getName(),
                            mudName(type),
                            friendlyTypeName(field.getType()),
                            field.getName(),
                            displayValue(field.get(object))));
                } catch (IllegalAccessException e) {
                    fields.add(new LpcObjectInspection.FieldValue(
                            type.getName(),
                            mudName(type),
                            friendlyTypeName(field.getType()),
                            field.getName(),
                            "<inaccessible>"));
                }
            }
            type = type.getSuperclass();
        }
        fields.sort(Comparator
                .comparing(LpcObjectInspection.FieldValue::ownerClass)
                .thenComparing(LpcObjectInspection.FieldValue::name));
        return fields;
    }

    private List<LpcObjectInspection.MethodSignature> inspectMethods(Object object) {
        List<LpcObjectInspection.MethodSignature> methods = new ArrayList<>();
        for (Method method : object.getClass().getMethods()) {
            if (method.isSynthetic() || method.isBridge() || method.getDeclaringClass() == Object.class) {
                continue;
            }
            if (!Modifier.isPublic(method.getModifiers())) {
                continue;
            }
            List<String> parameterTypes = new ArrayList<>();
            for (Class<?> parameterType : method.getParameterTypes()) {
                parameterTypes.add(friendlyTypeName(parameterType));
            }
            methods.add(new LpcObjectInspection.MethodSignature(
                    method.getDeclaringClass().getName(),
                    mudName(method.getDeclaringClass()),
                    friendlyTypeName(method.getReturnType()),
                    method.getName(),
                    parameterTypes));
        }
        methods.sort(Comparator
                .comparing(LpcObjectInspection.MethodSignature::name)
                .thenComparingInt(method -> method.parameterTypes().size())
                .thenComparing(LpcObjectInspection.MethodSignature::ownerClass));
        return methods;
    }

    private String mudName(Class<?> type) {
        return type.getName().replace('.', '/');
    }

    private String displayValue(Object value) {
        if (value == null) {
            return "0";
        }
        if (value instanceof String text) {
            return "\"" + text.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
        }
        if (value instanceof Number || value instanceof Boolean) {
            return value.toString();
        }
        return objectReference(value);
    }

    private String objectReference(Object object) {
        String objectId = runtimeContext.objectId(object);
        return objectId != null ? objectId : object.toString();
    }

    private String friendlyTypeName(Class<?> type) {
        if (type == void.class) {
            return "void";
        }
        if (type == int.class || type == Integer.class) {
            return "int";
        }
        if (type == boolean.class || type == Boolean.class) {
            return "status";
        }
        if (type == String.class) {
            return "string";
        }
        if (type == Object.class) {
            return "mixed";
        }
        return type.getSimpleName();
    }

    private Class<?> ensureClassDefined(Path sourcePath, String internalName) {
        if (classLoader.isDefined(internalName)) {
            try {
                return classLoader.loadClass(internalName.replace('/', '.'));
            } catch (ClassNotFoundException e) {
                throw new LpcRuntimeException("Defined LPC class could not be loaded: " + internalName, e);
            }
        }

        String source;
        try {
            source = Files.readString(sourcePath);
        } catch (IOException e) {
            throw new LpcRuntimeException("Failed to read source file: " + sourcePath, e);
        }

        CompilationResult result =
                pipeline.run(sourcePath, source, internalName, "/" + internalName, ParserOptions.defaults());
        if (!result.getProblems().isEmpty()) {
            throw new LpcRuntimeException(formatProblems(result.getProblems()), result.getProblems());
        }

        CompilationUnit compilationUnit = result.getCompilationUnit();
        if (compilationUnit != null) {
            defineInheritedClasses(compilationUnit.parentUnit());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LpcRuntimeException("Compilation did not produce bytecode for " + internalName);
        }

        return classLoader.defineClass(internalName, bytecode);
    }

    private void registerObject(String baseName, Object object) {
        String objectId = baseName;
        int suffix = 1;
        while (runtimeContext.getObject(objectId) != null) {
            objectId = baseName + "#" + suffix;
            suffix++;
        }
        runtimeContext.registerObject(objectId, object);
    }

    private String nextCloneId(String internalName) {
        String objectId = internalName + "#clone";
        int suffix = 1;
        while (runtimeContext.getObject(objectId) != null) {
            objectId = internalName + "#clone" + suffix;
            suffix++;
        }
        return objectId;
    }

    private Path resolveSourcePath(String sourcePath) {
        Path raw = Path.of(sourcePath);
        if (raw.isAbsolute() && baseIncludePath != null) {
            String trimmed = sourcePath;
            while (trimmed.startsWith("/")) {
                trimmed = trimmed.substring(1);
            }
            if (!trimmed.isEmpty()) {
                return baseIncludePath.resolve(trimmed).normalize();
            }
        }

        if (!raw.isAbsolute() && baseIncludePath != null) {
            return baseIncludePath.resolve(raw).normalize();
        }

        return raw.normalize();
    }

    private Path resolveSourcePathWithExtensions(String sourcePath) {
        Path resolved = resolveSourcePath(sourcePath);
        if (hasExtension(resolved)) {
            return resolved;
        }
        if (Files.exists(resolved)) {
            return resolved;
        }
        Path cCandidate = resolveSourcePath(sourcePath + ".c");
        if (Files.exists(cCandidate)) {
            return cCandidate;
        }
        Path lpcCandidate = resolveSourcePath(sourcePath + ".lpc");
        if (Files.exists(lpcCandidate)) {
            return lpcCandidate;
        }
        return resolved;
    }

    private Path resolveSourcePathWithExtensions(Path sourcePath) {
        Path normalized = normalizeSourcePath(sourcePath);
        if (hasExtension(sourcePath)) {
            return normalized;
        }
        if (Files.exists(normalized)) {
            return normalized;
        }
        Path cCandidate = normalizeSourcePath(appendExtension(sourcePath, ".c"));
        if (Files.exists(cCandidate)) {
            return cCandidate;
        }
        Path lpcCandidate = normalizeSourcePath(appendExtension(sourcePath, ".lpc"));
        if (Files.exists(lpcCandidate)) {
            return lpcCandidate;
        }
        return normalized;
    }

    private Path normalizeSourcePath(Path sourcePath) {
        Path normalized = sourcePath;
        if (!normalized.isAbsolute() && baseIncludePath != null) {
            normalized = baseIncludePath.resolve(normalized);
        }
        return normalized.toAbsolutePath().normalize();
    }

    private Path appendExtension(Path sourcePath, String extension) {
        Path fileName = sourcePath.getFileName();
        if (fileName == null) {
            return sourcePath;
        }
        Path parent = sourcePath.getParent();
        String nameWithExtension = fileName.toString() + extension;
        return (parent == null) ? Path.of(nameWithExtension) : parent.resolve(nameWithExtension);
    }

    private boolean hasExtension(Path sourcePath) {
        Path fileName = sourcePath.getFileName();
        if (fileName == null) {
            return false;
        }
        String name = fileName.toString();
        int dot = name.lastIndexOf('.');
        return dot > 0 && dot < name.length() - 1;
    }

    private String formatProblems(List<CompilationProblem> problems) {
        StringBuilder builder = new StringBuilder("Compilation failed:\n");
        for (CompilationProblem problem : problems) {
            builder.append("- ")
                    .append(problem.getStage())
                    .append(": ")
                    .append(problem.getMessage());
            if (problem.getLine() != null) {
                builder.append(" (line ").append(problem.getLine()).append(")");
            }
            Throwable throwable = problem.getThrowable();
            if ((throwable != null) && (throwable.getMessage() != null)) {
                builder.append(" - ").append(throwable.getMessage());
            }
            builder.append("\n");
        }
        return builder.toString();
    }

    private String normalizeInternalName(String internalName) {
        String normalized = internalName;
        while (normalized.startsWith("/")) {
            normalized = normalized.substring(1);
        }
        return normalized;
    }

    private String deriveSourceName(Path sourcePath, Path basePath) {
        Path normalized = sourcePath.normalize();
        Path base = (basePath != null) ? basePath.normalize() : null;
        Path relative = (base != null && normalized.startsWith(base))
                ? base.relativize(normalized)
                : normalized;
        Path withoutExtension = stripExtension(relative);
        String normalizedName = withoutExtension.normalize().toString().replace('\\', '/');

        while (normalizedName.startsWith("/")) {
            normalizedName = normalizedName.substring(1);
        }

        return normalizedName;
    }

    private String stripExtension(String name) {
        int dot = name.lastIndexOf('.');
        return (dot == -1) ? name : name.substring(0, dot);
    }

    private void defineInheritedClasses(CompilationUnit unit) {
        if (unit == null) {
            return;
        }

        defineInheritedClasses(unit.parentUnit());

        ASTObject astObject = unit.astObject();
        if (astObject == null) {
            return;
        }

        String internalName = normalizeInternalName(astObject.name());
        if (classLoader.isDefined(internalName)) {
            return;
        }

        CompilationResult result =
                pipeline.run(unit.sourcePath(), unit.source(), unit.sourceName(), unit.displayPath(), ParserOptions.defaults());

        if (!result.getProblems().isEmpty()) {
            throw new LpcRuntimeException(formatProblems(result.getProblems()), result.getProblems());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LpcRuntimeException("Compilation did not produce bytecode for " + internalName);
        }

        classLoader.defineClass(internalName, bytecode);
    }

    private Path stripExtension(Path path) {
        if (path == null) {
            return Path.of("<input>");
        }

        Path fileName = path.getFileName();
        if (fileName == null) {
            return path;
        }

        String name = fileName.toString();
        int dot = name.lastIndexOf('.');
        String stem = (dot == -1) ? name : name.substring(0, dot);
        Path parent = path.getParent();

        return (parent == null) ? Path.of(stem) : parent.resolve(stem);
    }
}
