/**
 * Lightweight runtime helpers consumed by generated bytecode.
 *
 * <p>Provides truthiness utilities aligned with LPC semantics plus a runtime type model that
 * captures JVM descriptors and truthiness semantics for IR and code generation.</p>
 *
 * <p>This layer is intentionally minimal; broader game-engine services or object models are expected
 * to live elsewhere.</p>
 */
package io.github.protasm.lpc2j.runtime;
