#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(dirname -- "$SCRIPT_DIR")
SOURCE_DIR="$ROOT_DIR/mudlibs/realmsmud/source"
OUTPUT_FILE="$SOURCE_DIR/init/init_file.full"
TMP_FILE="$OUTPUT_FILE.tmp"

if [ ! -d "$SOURCE_DIR" ]; then
  echo "RealmsMUD source directory not found: $SOURCE_DIR" >&2
  exit 1
fi

mkdir -p "$(dirname -- "$OUTPUT_FILE")"

{
  echo "# Full JVMud preload manifest for RealmsMUD."
  echo "# Generated by scripts/generate-realms-full-init.sh; do not edit by hand."
  echo
  find "$SOURCE_DIR" -type f -name '*.c' \
    | sed "s#^$SOURCE_DIR##" \
    | sort
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUTPUT_FILE"

count=$(grep -c '^/' "$OUTPUT_FILE" || true)
echo "Wrote $OUTPUT_FILE with $count object(s)."
