package io.github.protasm.jvmud.compiler.exec;

import io.github.protasm.jvmud.compiler.efun.Efun;
import io.github.protasm.jvmud.compiler.parser.ast.ASTObject;
import io.github.protasm.jvmud.compiler.pipeline.CompilationPipeline;
import io.github.protasm.jvmud.compiler.pipeline.CompilationProblem;
import io.github.protasm.jvmud.compiler.pipeline.CompilationResult;
import io.github.protasm.jvmud.compiler.pipeline.CompilationUnit;
import io.github.protasm.jvmud.compiler.parser.ParserOptions;
import io.github.protasm.jvmud.compiler.preproc.SearchPathIncludeResolver;
import io.github.protasm.jvmud.compiler.runtime.RuntimeContext;
import io.github.protasm.jvmud.compiler.runtime.RuntimeContextHolder;
import io.github.protasm.jvmud.engine.mudlib.MudlibBoundary;
import io.github.protasm.jvmud.engine.mudlib.MudlibLifecycleEvent;
import io.github.protasm.jvmud.engine.mudlib.MudlibProjection;
import io.github.protasm.jvmud.engine.identity.PersonaId;
import io.github.protasm.jvmud.engine.identity.PersonaRecord;
import io.github.protasm.jvmud.engine.identity.PlayerId;
import io.github.protasm.jvmud.engine.identity.PlayerRecord;
import io.github.protasm.jvmud.engine.identity.SessionId;
import io.github.protasm.jvmud.engine.identity.SessionRecord;
import io.github.protasm.jvmud.engine.time.WorldScheduler;
import io.github.protasm.jvmud.persistence.filesystem.LpcObjectStateStore;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.function.BiFunction;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Host-facing LPC execution runtime that owns classloading, object identity, and runtime context.
 *
 * <p>This runtime is distinct from {@code io.github.protasm.jvmud.compiler.runtime}, which contains the
 * language-level helpers used by generated bytecode. {@code LPCRuntime} sits above the compiler
 * pipeline and provides a minimal API for loading LPC objects from source code.</p>
 *
 * <p>The runtime registers shared objects before running compiler-generated LPC initialization so
 * benign circular singleton references can resolve an in-progress object. Direct recursive load
 * re-entry that cannot be resolved through a registered object still fails with a clear
 * {@link LPCRuntimeException}.</p>
 *
 * <p>Usage example:</p>
 *
 * <pre>{@code
 * LPCRuntime runtime = new LPCRuntime(LPCRuntimeConfig.builder()
 *         .baseIncludePath(Path.of("mudlibs", "lp245"))
 *         .build());
 * LPCObjectHandle orc = runtime.load("/obj/orc.c");
 * runtime.withRuntimeContext(() -> {
 *     orc.instance().getClass().getMethod("init").invoke(orc.instance());
 *     return null;
 * });
 * }</pre>
 */
public final class LPCRuntime {
    private static final String LPC_INIT_METHOD_NAME = "$lpc$init";

    private LPCRuntimeClassLoader classLoader;
    private final RuntimeContext runtimeContext;
    private final CompilationPipeline pipeline;
    private final Path baseIncludePath;
    private final List<Path> includeSearchPaths;
    private final List<String> loadingObjectIds = new ArrayList<>();
    private final LpcObjectStateStore objectStateStore = new LpcObjectStateStore();
    private final boolean useBoundaryMudlibRootForIncludes;
    private MudlibBoundary mudlibBoundary = MudlibBoundary.empty();
    private boolean notifyingCompilationError;
    private boolean notifyingTimedRuntimeError;
    private boolean notifyingObjectSourceMissing;
    private boolean notifyingObjectDestructionRequested;

    public LPCRuntime(LPCRuntimeConfig config) {
        Objects.requireNonNull(config, "config");
        this.baseIncludePath = config.baseIncludePath();
        this.includeSearchPaths = config.includeSearchPaths();
        this.useBoundaryMudlibRootForIncludes = config.includeResolver() == null;
        this.runtimeContext = new RuntimeContext(config.resolveIncludeResolver());
        this.runtimeContext.setObjectFactory(this::cloneObject);
        this.runtimeContext.setObjectLoader(this::loadOrGetObject);
        this.runtimeContext.setMudlibTextReader(this::readMudlibText);
        this.runtimeContext.setMudlibPathLister(this::listMudlibPaths);
        this.runtimeContext.setMudlibTextAppender(this::appendMudlibText);
        this.runtimeContext.setLPCObjectStateSaver(this::saveLPCObjectState);
        this.runtimeContext.setLPCObjectStateRestorer(this::restoreLPCObjectState);
        this.runtimeContext.setTimedRuntimeErrorHandler(this::notifyTimedRuntimeError);
        this.runtimeContext.setObjectDestructionRequestedHandler(this::notifyObjectDestructionRequested);
        this.classLoader = new LPCRuntimeClassLoader(config.parentClassLoader());
        this.pipeline = new CompilationPipeline(config.parentInternalName(), runtimeContext, config.compilationObserver());
    }

    /**
     * Loads, compiles, instantiates, registers, and initializes one LPC source file.
     *
     * <p>Relative paths are resolved under the configured base include path. Absolute-looking mudlib
     * paths such as {@code /room/church} are also resolved under that base path when one is
     * configured.</p>
     */
    public LPCObjectHandle load(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        return load(resolveSourcePathWithExtensions(sourcePath));
    }

    /**
     * Returns a registered shared object for a source path, loading it if needed.
     *
     * <p>This is the host-side equivalent of resolving a mudlib singleton object rather than making
     * a clone.</p>
     */
    public Object loadOrGetObject(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String objectId = normalizeInternalName(deriveSourceName(normalized, sourceNameBasePath(normalized)));
        Object existing = runtimeContext.getObject(objectId);
        if (existing != null) {
            return existing;
        }
        return load(normalized).instance();
    }

    /** Reloads an LPC source path, replacing the shared registered object if it already exists. */
    public LPCObjectHandle reload(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        return reload(resolveSourcePathWithExtensions(sourcePath));
    }

    /**
     * Reloads a source file from a filesystem path.
     *
     * <p>Reloading creates a fresh class loader because generated JVM classes cannot be redefined in
     * the same loader.</p>
     */
    public LPCObjectHandle reload(Path sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String objectId = normalizeInternalName(deriveSourceName(normalized, sourceNameBasePath(normalized)));
        Object existing = runtimeContext.getObject(objectId);
        if (existing != null) {
            runtimeContext.destructObject(existing);
        }

        // JVM classes cannot be redefined in the same classloader. A fresh loader lets the
        // reloaded LPC source produce a new generated class while old live objects keep working.
        classLoader = new LPCRuntimeClassLoader(classLoader.getParent());
        return load(normalized);
    }

    /** Loads, compiles, instantiates, registers, and initializes one source file. */
    public LPCObjectHandle load(Path sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String objectId = normalizeInternalName(deriveSourceName(normalized, sourceNameBasePath(normalized)));
        if (!Files.exists(normalized)) {
            Object supplied = notifyObjectSourceMissing(objectId);
            if (supplied != null) {
                return new LPCObjectHandle(this, objectId, supplied.getClass(), supplied);
            }
        }

        beginObjectLoad(objectId);
        try {
            return loadUnchecked(normalized, objectId);
        } finally {
            endObjectLoad(objectId);
        }
    }

    private LPCObjectHandle loadUnchecked(Path normalized, String objectId) {
        CompilationResult result = compile(normalized);

        if (!result.getProblems().isEmpty()) {
            throw compilationFailure(objectId, result.getProblems());
        }

        CompilationUnit compilationUnit = result.getCompilationUnit();
        if (compilationUnit != null) {
            defineInheritedClasses(compilationUnit.directParentUnits());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LPCRuntimeException("Compilation did not produce bytecode for " + objectId);
        }

        String internalName = (result.getAstObject() != null) ? result.getAstObject().name() : jvmInternalName(objectId);
        internalName = jvmInternalName(normalizeInternalName(internalName));
        Class<?> compiledClass = classLoader.defineClass(internalName, bytecode);
        Object instance = instantiate(compiledClass);

        registerObject(objectId, instance);
        try {
            initializeLPCObject(instance);
            resetIfPresent(instance);
        } catch (RuntimeException | Error e) {
            runtimeContext.destructObject(instance);
            throw e;
        }

        return new LPCObjectHandle(this, objectId, compiledClass, instance);
    }

    private void beginObjectLoad(String objectId) {
        if (loadingObjectIds.contains(objectId)) {
            List<String> cycle = new ArrayList<>(loadingObjectIds);
            cycle.add(objectId);
            throw new LPCRuntimeException("Circular LPC object load: " + String.join(" -> ", cycle));
        }
        loadingObjectIds.add(objectId);
    }

    private void endObjectLoad(String objectId) {
        int lastIndex = loadingObjectIds.size() - 1;
        if (lastIndex >= 0 && loadingObjectIds.get(lastIndex).equals(objectId)) {
            loadingObjectIds.remove(lastIndex);
            return;
        }
        loadingObjectIds.remove(objectId);
    }

    /** Compiles one source file using this runtime's include, efun, and mudlib boundary context. */
    public CompilationResult compile(Path sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String source;

        try {
            if (!Files.exists(normalized)) {
                String objectId = normalizeInternalName(deriveSourceName(normalized, sourceNameBasePath(normalized)));
                String message = "Source file not found: " + normalized;
                notifyCompilationError(objectId, message);
                throw new LPCRuntimeException(message);
            }
            source = Files.readString(normalized);
        } catch (IOException e) {
            String objectId = normalizeInternalName(deriveSourceName(normalized, sourceNameBasePath(normalized)));
            String message = "Failed to read source file: " + normalized;
            notifyCompilationError(objectId, message + ": " + e.getMessage());
            throw new LPCRuntimeException(message, e);
        }

        String objectId = normalizeInternalName(deriveSourceName(normalized, sourceNameBasePath(normalized)));
        String displayPath = "/" + objectId;
        return pipeline.run(normalized, source, jvmInternalName(objectId), displayPath, ParserOptions.defaults());
    }

    /** Attempts to load source and captures runtime failures as a result object. */
    public LPCLoadResult tryLoad(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        try {
            return LPCLoadResult.success(load(sourcePath));
        } catch (RuntimeException e) {
            return LPCLoadResult.failure(e);
        }
    }

    /** Attempts to load source and captures runtime failures as a result object. */
    public LPCLoadResult tryLoad(Path sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        try {
            return LPCLoadResult.success(load(sourcePath));
        } catch (RuntimeException e) {
            return LPCLoadResult.failure(e);
        }
    }

    /** Compiles and loads in-memory LPC source under the supplied source name. */
    public LPCObjectHandle loadSource(String sourceName, String source) {
        Objects.requireNonNull(sourceName, "sourceName");
        Objects.requireNonNull(source, "source");
        String objectId = normalizeInternalName(stripExtension(sourceName));
        String displayPath = "/" + objectId;

        CompilationResult result =
                pipeline.run(null, source, jvmInternalName(objectId), displayPath, ParserOptions.defaults());

        if (!result.getProblems().isEmpty()) {
            throw compilationFailure(objectId, result.getProblems());
        }

        CompilationUnit compilationUnit = result.getCompilationUnit();
        if (compilationUnit != null) {
            defineInheritedClasses(compilationUnit.directParentUnits());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LPCRuntimeException("Compilation did not produce bytecode for " + objectId);
        }

        String internalName = (result.getAstObject() != null) ? result.getAstObject().name() : jvmInternalName(objectId);
        internalName = jvmInternalName(normalizeInternalName(internalName));
        Class<?> compiledClass = classLoader.defineClass(internalName, bytecode);
        Object instance = instantiate(compiledClass);

        registerObject(objectId, instance);
        try {
            initializeLPCObject(instance);
            resetIfPresent(instance);
        } catch (RuntimeException | Error e) {
            runtimeContext.destructObject(instance);
            throw e;
        }

        return new LPCObjectHandle(this, objectId, compiledClass, instance);
    }

    /**
     * Creates a new clone of a compiled LPC object.
     *
     * <p>The source class is compiled if needed. Each clone receives a unique runtime object id.</p>
     */
    public Object cloneObject(String sourcePath) {
        Objects.requireNonNull(sourcePath, "sourcePath");
        Path normalized = resolveSourcePathWithExtensions(sourcePath);
        String objectId = normalizeInternalName(deriveSourceName(normalized, sourceNameBasePath(normalized)));
        String internalName = jvmInternalName(objectId);

        Class<?> objectClass = ensureClassDefined(normalized, objectId, internalName);
        Object instance = instantiate(objectClass);
        registerObject(nextCloneId(objectId), instance);
        try {
            initializeLPCObject(instance);
            resetIfPresent(instance);
        } catch (RuntimeException | Error e) {
            runtimeContext.destructObject(instance);
            throw e;
        }
        return instance;
    }

    /** Moves one runtime object into another object or into the shared object named by a path. */
    public void moveObject(Object object, Object destination) {
        if (destination instanceof String path) {
            destination = loadOrGetObject(path);
        }
        runtimeContext.moveObject(object, destination);
    }

    /** Returns the immediate runtime environment/container for an object. */
    public Object environment(Object object) {
        return runtimeContext.environment(object);
    }

    /** Resolves an object by identifier in a container, using current-context defaults when needed. */
    public Object present(Object identifier, Object container) {
        return runtimeContext.present(identifier, container);
    }

    /** Returns the first object contained by a runtime object. */
    public Object firstInventory(Object container) {
        return runtimeContext.firstInventory(container);
    }

    /** Returns the next sibling object in inventory traversal. */
    public Object nextInventory(Object object) {
        return runtimeContext.nextInventory(object);
    }

    /** Destructs a runtime object and removes it from object identity and containment indexes. */
    public void destructObject(Object object) {
        runtimeContext.destructObject(object);
    }

    /** Registers a host-created object under a mudlib-style object id. */
    public void registerHostObject(String objectId, Object object) {
        runtimeContext.registerObject(normalizeInternalName(objectId), object);
    }

    /** Returns the registered object id for an object, or {@code null} if it is not registered. */
    public String objectId(Object object) {
        return runtimeContext.objectId(object);
    }

    /** Reads a mudlib-relative text file, returning LPC false ({@code 0}) when unavailable. */
    public Object readMudlibText(String path) {
        Objects.requireNonNull(path, "path");
        Path resolved = resolveMudlibStoragePath(path);
        if (resolved == null || !Files.isRegularFile(resolved)) {
            resolved = resolveMudlibTextPath(path);
        }
        if (resolved == null || !Files.isRegularFile(resolved)) {
            return 0;
        }
        try {
            return Files.readString(resolved);
        } catch (IOException e) {
            return 0;
        }
    }

    /**
     * Lists mudlib-rooted files using the common LP {@code get_dir()} flag shape.
     *
     * <p>The initial JVMud contract supports the startup-critical name listing behavior: literal
     * paths or single-segment globs such as {@code /dir/*.sql}, sorted unless the unsorted bit is
     * set, and path-qualified names when the {@code GETDIR_PATH} bit is set. Metadata flags are
     * intentionally left for later expansion.</p>
     */
    public Object listMudlibPaths(String path, int flags) {
        Objects.requireNonNull(path, "path");
        MudlibListPattern pattern = mudlibListPattern(path);
        if (pattern == null) {
            return List.of();
        }

        Path directory = resolveMudlibTextPath(pattern.directory());
        if (directory == null || !Files.isDirectory(directory)) {
            directory = resolveMudlibStoragePath(pattern.directory());
        }
        if (directory == null || !Files.isDirectory(directory)) {
            return List.of();
        }

        List<String> entries = new ArrayList<>();
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(directory, pattern.glob())) {
            for (Path entry : stream) {
                String name = entry.getFileName().toString();
                entries.add((flags & 0x10) != 0
                        ? pattern.pathPrefix() + name
                        : name);
            }
        } catch (IOException e) {
            return List.of();
        }

        if ((flags & 0x20) == 0) {
            entries.sort(String::compareTo);
        }
        return entries;
    }

    /** Appends text to a mudlib-rooted file, returning LP-style success. */
    public int appendMudlibText(String path, Object text) {
        Objects.requireNonNull(path, "path");
        Path resolved = resolveMudlibTextPath(path);
        if (resolved == null) {
            resolved = resolveMudlibStoragePath(path);
        }
        if (resolved == null) {
            return 0;
        }
        try {
            Path parent = resolved.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            Files.writeString(
                    resolved,
                    String.valueOf(text),
                    java.nio.file.StandardOpenOption.CREATE,
                    java.nio.file.StandardOpenOption.APPEND);
            return 1;
        } catch (IOException e) {
            return 0;
        }
    }

    /** Saves scalar LPC object fields to mudlib-rooted storage, returning LP-style success. */
    public int saveLPCObjectState(String path, Object object) {
        Objects.requireNonNull(path, "path");
        Objects.requireNonNull(object, "object");
        Path resolved = resolveMudlibStoragePath(path + ".o");
        if (resolved == null) {
            return 0;
        }

        return objectStateStore.save(resolved, object);
    }

    /** Restores scalar LPC object fields from mudlib-rooted storage, returning LP-style success. */
    public int restoreLPCObjectState(String path, Object object) {
        Objects.requireNonNull(path, "path");
        Objects.requireNonNull(object, "object");
        Path resolved = resolveMudlibStoragePath(path + ".o");
        if (resolved == null) {
            return 0;
        }
        return objectStateStore.restore(resolved, object);
    }

    /** Returns the active mudlib boundary metadata. */
    public MudlibBoundary mudlibBoundary() {
        return mudlibBoundary;
    }

    /** Registers mudlib boundary metadata and updates generated-code helper configuration. */
    public void registerMudlibBoundary(MudlibBoundary mudlibBoundary) {
        this.mudlibBoundary = Objects.requireNonNull(mudlibBoundary, "mudlibBoundary");
        runtimeContext.setMudlibBoundary(mudlibBoundary);
        runtimeContext.setMfunObjectPath(mudlibBoundary.mfunObjectPath().orElse(null));
        if (useBoundaryMudlibRootForIncludes) {
            mudlibBoundary.mudlibRootPath().ifPresent(root ->
                    runtimeContext.setIncludeResolver(new SearchPathIncludeResolver(root, includeSearchPaths)));
        }
    }

    /** Connects this LPC runtime to the deterministic scheduler for its owning world. */
    public void setScheduler(WorldScheduler scheduler) {
        runtimeContext.setScheduler(scheduler);
    }

    /** Invokes a public LPC method with this runtime installed as the current generated-code context. */
    public Object invokeObject(Object object, String methodName, Object... args) {
        return withRuntimeContext(() -> runtimeContext.invokeObject(object, methodName, args));
    }

    /** Invokes a public LPC method when present, returning 0 if the object does not implement it. */
    public Object invokeOptionalObject(Object object, String methodName, Object... args) {
        return withRuntimeContext(() -> runtimeContext.invokeOptionalObject(object, methodName, args));
    }

    /**
     * Rebuilds command actions for a Persona from nearby mudlib objects.
     *
     * <p>This invokes the configured interaction-scope lifecycle method on the Persona, its
     * environment, and immediately nearby inventory objects so LPC {@code init}/{@code add_action}
     * style registrations can be refreshed.</p>
     */
    public void refreshCommandActions(Object actor) {
        Objects.requireNonNull(actor, "actor");
        withRuntimeContext(() -> runtimeContext.withCommandActor(actor, () -> {
            runtimeContext.clearCommandActions(actor);
            runtimeContext.clearPendingActionMethods();
            try {
                return runtimeContext.withScopedCommandRegistration(() -> {
                invokeLifecycleIfPresent(MudlibLifecycleEvent.INTERACTION_SCOPE_STARTED, actor);
                Object environment = runtimeContext.environment(actor);
                if (environment != null) {
                    invokeLifecycleIfPresent(MudlibLifecycleEvent.INTERACTION_SCOPE_STARTED, environment);
                    forEachInventory(environment, object ->
                            invokeLifecycleIfPresent(MudlibLifecycleEvent.INTERACTION_SCOPE_STARTED, object));
                }
                forEachInventory(actor, object ->
                        invokeLifecycleIfPresent(MudlibLifecycleEvent.INTERACTION_SCOPE_STARTED, object));
                    return null;
                });
            } finally {
                runtimeContext.clearPendingActionMethods();
            }
        }));
    }

    /** Dispatches one player command line through the Persona's registered command actions. */
    public Object dispatchCommand(Object actor, String commandLine) {
        Objects.requireNonNull(actor, "actor");
        Objects.requireNonNull(commandLine, "commandLine");
        return withRuntimeContext(() -> runtimeContext.withCommandActor(actor, () ->
                runtimeContext.dispatchCommand(actor, commandLine)));
    }

    /** Runs an operation with the supplied object as the active command actor. */
    public <T> T withCommandActor(Object actor, Supplier<T> action) {
        Objects.requireNonNull(actor, "actor");
        Objects.requireNonNull(action, "action");
        return withRuntimeContext(() -> runtimeContext.withCommandActor(actor, action));
    }

    /** Returns whether a persona is waiting for captured session input. */
    public boolean hasCapturedSessionInput(Object persona) {
        Objects.requireNonNull(persona, "persona");
        return runtimeContext.hasCapturedSessionInput(persona);
    }

    /** Returns whether the pending captured input should suppress terminal echo. */
    public boolean capturedSessionInputNoEcho(Object persona) {
        Objects.requireNonNull(persona, "persona");
        return runtimeContext.capturedSessionInputNoEcho(persona);
    }

    /** Delivers one captured input line to a persona. */
    public Object deliverCapturedSessionInput(Object persona, String line) {
        Objects.requireNonNull(persona, "persona");
        Objects.requireNonNull(line, "line");
        return withRuntimeContext(() -> runtimeContext.deliverCapturedSessionInput(persona, line));
    }

    /** Builds a reflection-backed inspection snapshot for admin tooling. */
    public LPCObjectInspection inspectObject(Object object) {
        Objects.requireNonNull(object, "object");
        Object environment = runtimeContext.environment(object);
        List<String> inventoryIds = new ArrayList<>();
        Object child = runtimeContext.firstInventory(object);
        while (child != null) {
            inventoryIds.add(objectReference(child));
            child = runtimeContext.nextInventory(child);
        }

        return new LPCObjectInspection(
                runtimeContext.objectId(object),
                object.getClass().getName(),
                environment == null ? null : objectReference(environment),
                inventoryIds,
                inspectFields(object),
                inspectMethods(object));
    }

    /** Registers one LPC-facing engine function in this runtime. */
    public void registerEfun(Efun efun) {
        runtimeContext.registerEfun(efun);
    }

    /** Sets the server-owned handler for moving the active Player between hosted games. */
    public void setPlayerTransferHandler(BiFunction<Object, String, Integer> playerTransferHandler) {
        runtimeContext.setPlayerTransferHandler(playerTransferHandler);
    }

    /** Sets the default output sink used for runtime text delivery. */
    public void setOutputSink(Consumer<String> outputSink) {
        runtimeContext.setOutputSink(outputSink);
    }

    /** Binds a host session id to an engine Player before a Persona has been resolved. */
    public void bindPlayerSession(String sessionId, String remoteAddress, Consumer<String> sessionOutputSink) {
        runtimeContext.bindPlayerSession(sessionId, remoteAddress, sessionOutputSink);
    }

    /** Binds a host session id to a persona and session-specific output sink. */
    public void bindSession(String sessionId, Object persona, String remoteAddress, Consumer<String> sessionOutputSink) {
        runtimeContext.bindSession(sessionId, persona, remoteAddress, sessionOutputSink);
    }

    /** Binds a host session id to a persona with an explicit mudlib compatibility projection. */
    public void bindSession(
            String sessionId,
            Object persona,
            String remoteAddress,
            Consumer<String> sessionOutputSink,
            MudlibProjection mudlibProjection) {
        runtimeContext.bindSession(sessionId, persona, remoteAddress, sessionOutputSink, mudlibProjection);
    }

    /** Removes a host session binding. */
    public void unbindSession(String sessionId) {
        runtimeContext.unbindSession(sessionId);
    }

    /** Returns the engine-owned Session record for a bound host session. */
    public Optional<SessionRecord> sessionRecord(String sessionId) {
        return runtimeContext.sessionRecord(sessionId);
    }

    /** Returns the engine-owned Player record associated with a bound host session. */
    public Optional<PlayerRecord> playerRecordForSession(String sessionId) {
        return runtimeContext.playerRecordForSession(sessionId);
    }

    /** Returns the engine-owned Persona record associated with a compatibility persona projection. */
    public Optional<PersonaRecord> personaRecordForProjection(Object persona) {
        return runtimeContext.personaRecordForProjection(persona);
    }

    /** Delivers engine control-plane or transport text to one bound Session. */
    public boolean messageSession(SessionId sessionId, Object value) {
        return runtimeContext.messageSession(sessionId, value);
    }

    /** Delivers engine control-plane text to all active Sessions for one Player. */
    public boolean messagePlayer(PlayerId playerId, Object value) {
        return runtimeContext.messagePlayer(playerId, value);
    }

    /** Delivers engine gameplay text to one bound Persona. */
    public boolean messagePersona(PersonaId personaId, Object value) {
        return runtimeContext.messagePersona(personaId, value);
    }

    /** Returns the accumulated default output transcript for diagnostics and tests. */
    public String outputTranscript() {
        return runtimeContext.outputTranscript();
    }

    /** Clears the accumulated default output transcript. */
    public void clearOutputTranscript() {
        runtimeContext.clearOutputTranscript();
    }

    /** Runs an action with this runtime installed as the current generated-code context. */
    public <T> T withRuntimeContext(Supplier<T> action) {
        Objects.requireNonNull(action, "action");
        RuntimeContext previous = RuntimeContextHolder.current();
        RuntimeContextHolder.setCurrent(runtimeContext);
        try {
            return action.get();
        } finally {
            RuntimeContextHolder.setCurrent(previous);
        }
    }

    /** Runs an action with this runtime and a current LPC object installed. */
    public <T> T withCurrentObject(Object object, Supplier<T> action) {
        Objects.requireNonNull(action, "action");
        return withRuntimeContext(() -> runtimeContext.withCurrentObject(object, action));
    }

    /** Runnable convenience wrapper for {@link #withCurrentObject(Object, Supplier)}. */
    public void runWithCurrentObject(Object object, Runnable action) {
        Objects.requireNonNull(action, "action");
        withCurrentObject(object, () -> {
            action.run();
            return null;
        });
    }

    /** Runnable convenience wrapper for {@link #withRuntimeContext(Supplier)}. */
    public void runWithRuntimeContext(Runnable action) {
        Objects.requireNonNull(action, "action");
        withRuntimeContext(() -> {
            action.run();
            return null;
        });
    }

    private Object instantiate(Class<?> compiledClass) {
        return withRuntimeContext(() -> {
            try {
                return compiledClass.getDeclaredConstructor().newInstance();
            } catch (InstantiationException
                    | IllegalAccessException
                    | InvocationTargetException
                    | NoSuchMethodException e) {
                throw new LPCRuntimeException("Failed to instantiate LPC object: " + compiledClass.getName(), e);
            }
        });
    }

    /**
     * Runs compiler-generated LPC field initialization after the host runtime has registered the
     * object id.
     *
     * <p>Generated constructors deliberately stay Java-only. Deferring {@code $lpc$init} until after
     * registration lets benign circular singleton references resolve the in-progress object through
     * {@link #loadOrGetObject(String)} instead of recursively constructing a second instance.</p>
     */
    private void initializeLPCObject(Object object) {
        withRuntimeContext(() -> {
            try {
                Method method = object.getClass().getDeclaredMethod(LPC_INIT_METHOD_NAME);
                method.setAccessible(true);
                method.invoke(object);
                return null;
            } catch (NoSuchMethodException e) {
                return null;
            } catch (IllegalAccessException e) {
                throw new LPCRuntimeException("Failed to initialize LPC object: " + object.getClass().getName(), e);
            } catch (InvocationTargetException e) {
                Throwable targetException = e.getTargetException();
                if (targetException instanceof RuntimeException runtimeException) {
                    throw runtimeException;
                }
                if (targetException instanceof Error error) {
                    throw error;
                }
                throw new LPCRuntimeException("Failed to initialize LPC object: " + object.getClass().getName(),
                        targetException);
            }
        });
    }

    private void forEachInventory(Object container, Consumer<Object> action) {
        Object child = runtimeContext.firstInventory(container);
        while (child != null) {
            Object next = runtimeContext.nextInventory(child);
            action.accept(child);
            child = next;
        }
    }

    private void resetIfPresent(Object object) {
        invokeLifecycleIfPresent(MudlibLifecycleEvent.OBJECT_LOADED, object, 0);
    }

    private void invokeLifecycleIfPresent(MudlibLifecycleEvent event, Object object, Object... args) {
        String methodName = mudlibBoundary.lifecycleMethod(event).orElse(null);
        if (methodName == null) {
            return;
        }

        withRuntimeContext(() -> runtimeContext.invokeOptionalObject(object, methodName, args));
    }

    private Class<?>[] parameterTypes(Object[] args) {
        Class<?>[] types = new Class<?>[args.length];
        for (int i = 0; i < args.length; i++) {
            types[i] = Object.class;
        }
        return types;
    }

    private List<LPCObjectInspection.FieldValue> inspectFields(Object object) {
        List<LPCObjectInspection.FieldValue> fields = new ArrayList<>();
        Class<?> type = object.getClass();
        while (type != null && type != Object.class) {
            for (Field field : type.getDeclaredFields()) {
                if (field.isSynthetic()) {
                    continue;
                }
                try {
                    field.setAccessible(true);
                    fields.add(new LPCObjectInspection.FieldValue(
                            type.getName(),
                            mudName(type),
                            friendlyTypeName(field.getType()),
                            field.getName(),
                            displayValue(field.get(object))));
                } catch (IllegalAccessException e) {
                    fields.add(new LPCObjectInspection.FieldValue(
                            type.getName(),
                            mudName(type),
                            friendlyTypeName(field.getType()),
                            field.getName(),
                            "<inaccessible>"));
                }
            }
            type = type.getSuperclass();
        }
        fields.sort(Comparator
                .comparing(LPCObjectInspection.FieldValue::ownerClass)
                .thenComparing(LPCObjectInspection.FieldValue::name));
        return fields;
    }

    private List<LPCObjectInspection.MethodSignature> inspectMethods(Object object) {
        List<LPCObjectInspection.MethodSignature> methods = new ArrayList<>();
        for (Method method : object.getClass().getMethods()) {
            if (method.isSynthetic() || method.isBridge() || method.getDeclaringClass() == Object.class) {
                continue;
            }
            if (!Modifier.isPublic(method.getModifiers())) {
                continue;
            }
            List<String> parameterTypes = new ArrayList<>();
            for (Class<?> parameterType : method.getParameterTypes()) {
                parameterTypes.add(friendlyTypeName(parameterType));
            }
            methods.add(new LPCObjectInspection.MethodSignature(
                    method.getDeclaringClass().getName(),
                    mudName(method.getDeclaringClass()),
                    friendlyTypeName(method.getReturnType()),
                    method.getName(),
                    parameterTypes));
        }
        methods.sort(Comparator
                .comparing(LPCObjectInspection.MethodSignature::name)
                .thenComparingInt(method -> method.parameterTypes().size())
                .thenComparing(LPCObjectInspection.MethodSignature::ownerClass));
        return methods;
    }

    private String mudName(Class<?> type) {
        return type.getName().replace('.', '/');
    }

    private String displayValue(Object value) {
        if (value == null) {
            return "0";
        }
        if (value instanceof String text) {
            return "\"" + text.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
        }
        if (value instanceof Number || value instanceof Boolean) {
            return value.toString();
        }
        return objectReference(value);
    }

    private String objectReference(Object object) {
        String objectId = runtimeContext.objectId(object);
        return objectId != null ? objectId : object.toString();
    }

    private String friendlyTypeName(Class<?> type) {
        if (type == void.class) {
            return "void";
        }
        if (type == int.class || type == Integer.class) {
            return "int";
        }
        if (type == boolean.class || type == Boolean.class) {
            return "status";
        }
        if (type == String.class) {
            return "string";
        }
        if (type == Object.class) {
            return "mixed";
        }
        return type.getSimpleName();
    }

    private Class<?> ensureClassDefined(Path sourcePath, String objectId, String internalName) {
        if (classLoader.isDefined(internalName)) {
            try {
                return classLoader.loadClass(internalName.replace('/', '.'));
            } catch (ClassNotFoundException e) {
                throw new LPCRuntimeException("Defined LPC class could not be loaded: " + internalName, e);
            }
        }

        String source;
        try {
            source = Files.readString(sourcePath);
        } catch (IOException e) {
            throw new LPCRuntimeException("Failed to read source file: " + sourcePath, e);
        }

        CompilationResult result =
                pipeline.run(sourcePath, source, internalName, "/" + objectId, ParserOptions.defaults());
        if (!result.getProblems().isEmpty()) {
            throw compilationFailure(objectId, result.getProblems());
        }

        CompilationUnit compilationUnit = result.getCompilationUnit();
        if (compilationUnit != null) {
            defineInheritedClasses(compilationUnit.directParentUnits());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LPCRuntimeException("Compilation did not produce bytecode for " + internalName);
        }

        return classLoader.defineClass(internalName, bytecode);
    }

    private void registerObject(String baseName, Object object) {
        String objectId = baseName;
        int suffix = 1;
        while (runtimeContext.getObject(objectId) != null) {
            objectId = baseName + "#" + suffix;
            suffix++;
        }
        runtimeContext.registerObject(objectId, object);
    }

    private String nextCloneId(String internalName) {
        String objectId = internalName + "#clone";
        int suffix = 1;
        while (runtimeContext.getObject(objectId) != null) {
            objectId = internalName + "#clone" + suffix;
            suffix++;
        }
        return objectId;
    }

    private Path resolveSourcePath(String sourcePath) {
        Path raw = Path.of(sourcePath);
        if (raw.isAbsolute() && baseIncludePath != null) {
            String trimmed = sourcePath;
            while (trimmed.startsWith("/")) {
                trimmed = trimmed.substring(1);
            }
            if (!trimmed.isEmpty()) {
                Path baseCandidate = baseIncludePath.resolve(trimmed).normalize();
                if (Files.exists(baseCandidate)) {
                    return baseCandidate;
                }
                Path mudlibRoot = mudlibBoundary.mudlibRootPath().orElse(null);
                if (mudlibRoot != null) {
                    Path mudlibCandidate = mudlibRoot.resolve(trimmed).normalize();
                    if (Files.exists(mudlibCandidate)) {
                        return mudlibCandidate;
                    }
                }
                return baseCandidate;
            }
        }

        if (!raw.isAbsolute() && baseIncludePath != null) {
            Path baseCandidate = baseIncludePath.resolve(raw).normalize();
            if (Files.exists(baseCandidate)) {
                return baseCandidate;
            }
            Path mudlibRoot = mudlibBoundary.mudlibRootPath().orElse(null);
            if (mudlibRoot != null) {
                Path mudlibCandidate = mudlibRoot.resolve(raw).normalize();
                if (Files.exists(mudlibCandidate)) {
                    return mudlibCandidate;
                }
            }
            return baseCandidate;
        }

        return raw.normalize();
    }

    private Path resolveMudlibStoragePath(String path) {
        if (baseIncludePath == null) {
            return null;
        }
        String normalized = normalizeMudlibStoragePath(path);
        if (normalized == null) {
            return null;
        }
        return resolveMudlibPathUnder(baseIncludePath, normalized);
    }

    private Path resolveMudlibTextPath(String path) {
        Path mudlibRoot = mudlibBoundary.mudlibRootPath().orElse(null);
        if (mudlibRoot == null) {
            return null;
        }
        String normalized = normalizeMudlibStoragePath(path);
        if (normalized == null) {
            return null;
        }
        return resolveMudlibPathUnder(mudlibRoot, normalized);
    }

    private String normalizeMudlibStoragePath(String path) {
        String normalized = path.trim();
        while (normalized.startsWith("/")) {
            normalized = normalized.substring(1);
        }
        if (normalized.isBlank()) {
            return null;
        }
        for (Path segment : Path.of(normalized)) {
            if (segment.toString().equals("..")) {
                return null;
            }
        }
        return normalized;
    }

    private Path resolveMudlibPathUnder(Path root, String normalizedPath) {
        Path normalizedRoot = root.toAbsolutePath().normalize();
        Path resolved = normalizedRoot.resolve(normalizedPath).normalize();
        return resolved.startsWith(normalizedRoot) ? resolved : null;
    }

    private MudlibListPattern mudlibListPattern(String path) {
        String normalized = path.trim();
        while (normalized.startsWith("/")) {
            normalized = normalized.substring(1);
        }
        for (Path segment : Path.of(normalized.isEmpty() ? "." : normalized)) {
            if (segment.toString().equals("..")) {
                return null;
            }
        }
        int slash = normalized.lastIndexOf('/');
        String directory = slash >= 0 ? normalized.substring(0, slash) : "";
        String glob = slash >= 0 ? normalized.substring(slash + 1) : normalized;
        if (glob.isEmpty()) {
            glob = "*";
        }
        String pathPrefix = "/" + (directory.isEmpty() ? "" : directory + "/");
        return new MudlibListPattern(directory.isEmpty() ? "." : directory, glob, pathPrefix);
    }

    private record MudlibListPattern(String directory, String glob, String pathPrefix) {}

    private Path resolveSourcePathWithExtensions(String sourcePath) {
        Path resolved = resolveSourcePath(sourcePath);
        if (hasExtension(resolved)) {
            return resolved;
        }
        if (Files.isRegularFile(resolved)) {
            return resolved;
        }
        Path cCandidate = resolveSourcePath(sourcePath + ".c");
        if (Files.isRegularFile(cCandidate)) {
            return cCandidate;
        }
        Path lpcCandidate = resolveSourcePath(sourcePath + ".lpc");
        if (Files.isRegularFile(lpcCandidate)) {
            return lpcCandidate;
        }
        return resolved;
    }

    private Path resolveSourcePathWithExtensions(Path sourcePath) {
        Path normalized = normalizeSourcePath(sourcePath);
        if (hasExtension(sourcePath)) {
            return normalized;
        }
        if (Files.isRegularFile(normalized)) {
            return normalized;
        }
        Path cCandidate = normalizeSourcePath(appendExtension(sourcePath, ".c"));
        if (Files.isRegularFile(cCandidate)) {
            return cCandidate;
        }
        Path lpcCandidate = normalizeSourcePath(appendExtension(sourcePath, ".lpc"));
        if (Files.isRegularFile(lpcCandidate)) {
            return lpcCandidate;
        }
        return normalized;
    }

    private Path normalizeSourcePath(Path sourcePath) {
        Path normalized = sourcePath;
        if (!normalized.isAbsolute() && baseIncludePath != null) {
            normalized = baseIncludePath.resolve(normalized);
        }
        return normalized.toAbsolutePath().normalize();
    }

    private Path sourceNameBasePath(Path sourcePath) {
        Path mudlibRoot = mudlibBoundary.mudlibRootPath().orElse(null);
        if (mudlibRoot != null && sourcePath.normalize().startsWith(mudlibRoot.normalize())) {
            return mudlibRoot;
        }
        return baseIncludePath;
    }

    private Path appendExtension(Path sourcePath, String extension) {
        Path fileName = sourcePath.getFileName();
        if (fileName == null) {
            return sourcePath;
        }
        Path parent = sourcePath.getParent();
        String nameWithExtension = fileName.toString() + extension;
        return (parent == null) ? Path.of(nameWithExtension) : parent.resolve(nameWithExtension);
    }

    private boolean hasExtension(Path sourcePath) {
        Path fileName = sourcePath.getFileName();
        if (fileName == null) {
            return false;
        }
        String name = fileName.toString();
        return name.endsWith(".c") || name.endsWith(".lpc");
    }

    private String formatProblems(List<CompilationProblem> problems) {
        StringBuilder builder = new StringBuilder("Compilation failed:\n");
        for (CompilationProblem problem : problems) {
            builder.append("- ")
                    .append(problem.getStage())
                    .append(": ")
                    .append(problem.getMessage());
            if (problem.getLine() != null) {
                builder.append(" (line ").append(problem.getLine()).append(")");
            }
            Throwable throwable = problem.getThrowable();
            if ((throwable != null) && (throwable.getMessage() != null)) {
                builder.append(" - ").append(throwable.getMessage());
            }
            builder.append("\n");
        }
        return builder.toString();
    }

    private LPCRuntimeException compilationFailure(String objectId, List<CompilationProblem> problems) {
        String message = formatProblems(problems);
        notifyCompilationError(objectId, message);
        return new LPCRuntimeException(message, problems);
    }

    /**
     * Gives the mudlib a chance to satisfy a shared-object path whose source file is absent.
     *
     * <p>This is intentionally phrased as a missing-source hook rather than a virtual-object
     * primitive. JVMud only knows that normal source lookup failed for {@code objectId}. If the
     * mudlib returns an already-registered runtime object, that object becomes the canonical shared
     * object for {@code objectId}; future {@link #loadOrGetObject(String)} calls return it from the
     * object table before touching the filesystem or notifying the mudlib again. Returning LPC
     * false, or returning a non-object scalar by mistake, keeps the ordinary source-not-found path,
     * including compile-error notification.</p>
     */
    private Object notifyObjectSourceMissing(String objectId) {
        String methodName = mudlibBoundary.lifecycleMethod(MudlibLifecycleEvent.OBJECT_SOURCE_MISSING).orElse(null);
        String boundaryObjectPath = mudlibBoundary.boundaryObjectPath().orElse(null);
        if (methodName == null || boundaryObjectPath == null || notifyingObjectSourceMissing) {
            return null;
        }

        String normalizedObjectId = normalizeInternalName(objectId);
        String normalizedBoundaryPath = normalizeInternalName(boundaryObjectPath);
        if (normalizedBoundaryPath.equals(normalizedObjectId)) {
            return null;
        }

        notifyingObjectSourceMissing = true;
        try {
            Object handler = loadOrGetObject(normalizedBoundaryPath);
            Object supplied = invokeOptionalObject(handler, methodName, normalizedObjectId);
            clearOutputTranscript();
            if (isLpcFalse(supplied)) {
                return null;
            }
            if (runtimeContext.objectId(supplied) == null) {
                return null;
            }
            runtimeContext.registerObject(normalizedObjectId, supplied);
            return supplied;
        } catch (RuntimeException | LinkageError ignored) {
            clearOutputTranscript();
            return null;
        } finally {
            notifyingObjectSourceMissing = false;
        }
    }

    private void notifyCompilationError(String objectId, String message) {
        String methodName = mudlibBoundary.lifecycleMethod(MudlibLifecycleEvent.LOG_ERROR).orElse(null);
        String boundaryObjectPath = mudlibBoundary.boundaryObjectPath().orElse(null);
        if (methodName == null || boundaryObjectPath == null || notifyingCompilationError) {
            return;
        }

        String normalizedObjectId = normalizeInternalName(objectId);
        String normalizedBoundaryPath = normalizeInternalName(boundaryObjectPath);
        if (normalizedBoundaryPath.equals(normalizedObjectId)) {
            return;
        }

        notifyingCompilationError = true;
        try {
            Object handler = loadOrGetObject(normalizedBoundaryPath);
            invokeOptionalObject(handler, methodName, "/" + normalizedObjectId, message);
            clearOutputTranscript();
        } catch (RuntimeException | LinkageError ignored) {
            clearOutputTranscript();
        } finally {
            notifyingCompilationError = false;
        }
    }

    private void notifyTimedRuntimeError(Object target, String context, String operation, Throwable error) {
        String boundaryObjectPath = mudlibBoundary.boundaryObjectPath().orElse(null);
        if (boundaryObjectPath == null || notifyingTimedRuntimeError) {
            return;
        }

        notifyingTimedRuntimeError = true;
        try {
            Object handler = loadOrGetObject(boundaryObjectPath);
            String detail = error.getMessage() != null ? error.getMessage() : error.getClass().getSimpleName();
            String objectId = runtimeContext.objectId(target);
            if (objectId == null) {
                objectId = String.valueOf(target);
            }

            String runtimeErrorMethod = mudlibBoundary.lifecycleMethod(MudlibLifecycleEvent.RUNTIME_ERROR).orElse(null);
            if (runtimeErrorMethod != null) {
                invokeOptionalObject(handler, runtimeErrorMethod, target, context, operation, detail);
                clearOutputTranscript();
            }

            if ("scheduled_tick".equals(context)) {
                String scheduledTickErrorMethod =
                        mudlibBoundary.lifecycleMethod(MudlibLifecycleEvent.SCHEDULED_TICK_ERROR).orElse(null);
                if (scheduledTickErrorMethod != null) {
                    invokeOptionalObject(handler, scheduledTickErrorMethod, target, detail, objectId, objectId, 0);
                    clearOutputTranscript();
                }
            }
        } catch (RuntimeException | LinkageError ignored) {
            clearOutputTranscript();
        } finally {
            notifyingTimedRuntimeError = false;
        }
    }

    private Object notifyObjectDestructionRequested(Object target) {
        String methodName = mudlibBoundary.lifecycleMethod(MudlibLifecycleEvent.OBJECT_DESTRUCTION_REQUESTED).orElse(null);
        String boundaryObjectPath = mudlibBoundary.boundaryObjectPath().orElse(null);
        if (methodName == null || boundaryObjectPath == null || notifyingObjectDestructionRequested) {
            return 0;
        }

        notifyingObjectDestructionRequested = true;
        try {
            Object handler = loadOrGetObject(boundaryObjectPath);
            Object result = invokeOptionalObject(handler, methodName, target);
            clearOutputTranscript();
            return result;
        } catch (RuntimeException | LinkageError e) {
            clearOutputTranscript();
            return 1;
        } finally {
            notifyingObjectDestructionRequested = false;
        }
    }

    private boolean isLpcFalse(Object value) {
        return value == null || Integer.valueOf(0).equals(value);
    }

    private String normalizeInternalName(String internalName) {
        String normalized = internalName;
        while (normalized.startsWith("/")) {
            normalized = normalized.substring(1);
        }
        return normalized;
    }

    private String jvmInternalName(String objectId) {
        return objectId.replace(".", "$dot$");
    }

    private String deriveSourceName(Path sourcePath, Path basePath) {
        Path normalized = sourcePath.normalize();
        Path base = (basePath != null) ? basePath.normalize() : null;
        Path relative = (base != null && normalized.startsWith(base))
                ? base.relativize(normalized)
                : normalized;
        Path withoutExtension = stripExtension(relative);
        String normalizedName = withoutExtension.normalize().toString().replace('\\', '/');

        while (normalizedName.startsWith("/")) {
            normalizedName = normalizedName.substring(1);
        }

        return normalizedName;
    }

    private String stripExtension(String name) {
        int dot = name.lastIndexOf('.');
        return (dot == -1) ? name : name.substring(0, dot);
    }

    /** Defines every direct inherited LPC class, including secondary multiple-inherit parents. */
    private void defineInheritedClasses(List<CompilationUnit> units) {
        if (units == null || units.isEmpty()) {
            return;
        }

        for (CompilationUnit unit : units) {
            defineInheritedClasses(unit);
        }
    }

    /** Defines one inherited LPC class after recursively defining its own inherited classes. */
    private void defineInheritedClasses(CompilationUnit unit) {
        if (unit == null) {
            return;
        }

        defineInheritedClasses(unit.directParentUnits());

        ASTObject astObject = unit.astObject();
        if (astObject == null) {
            return;
        }

        String internalName = normalizeInternalName(astObject.name());
        if (classLoader.isDefined(internalName)) {
            return;
        }

        CompilationResult result =
                pipeline.run(unit.sourcePath(), unit.source(), unit.sourceName(), unit.displayPath(), ParserOptions.defaults());

        if (!result.getProblems().isEmpty()) {
            throw compilationFailure(internalName, result.getProblems());
        }

        byte[] bytecode = result.getBytecode();
        if (bytecode == null) {
            throw new LPCRuntimeException("Compilation did not produce bytecode for " + internalName);
        }

        classLoader.defineClass(internalName, bytecode);
    }

    private Path stripExtension(Path path) {
        if (path == null) {
            return Path.of("<input>");
        }

        Path fileName = path.getFileName();
        if (fileName == null) {
            return path;
        }

        String name = fileName.toString();
        int dot = name.lastIndexOf('.');
        String stem = (dot == -1) ? name : name.substring(0, dot);
        Path parent = path.getParent();

        return (parent == null) ? Path.of(stem) : parent.resolve(stem);
    }
}
