/**
 * Host-facing LPC execution runtime.
 *
 * <p>This package sits above the compiler pipeline. It resolves LPC source paths, runs compilation,
 * defines generated JVM classes, instantiates LPC objects, registers shared object identities, and
 * exposes invocation helpers for tests, server code, and tools.</p>
 *
 * <p>It is intentionally separate from {@code io.github.protasm.jvmud.compiler.runtime}, which
 * contains support code consumed by generated bytecode, and from {@code
 * io.github.protasm.jvmud.engine}, which owns JVMud world ontology.</p>
 */
package io.github.protasm.jvmud.compiler.exec;
