/**
 * Interfaces and registry for LPC efuns (built-in functions).
 *
 * <p>Defines the {@link io.github.protasm.lpc2j.efun.Efun} contract, the {@link
 * io.github.protasm.lpc2j.efun.EfunSignature} metadata, and an instance-scoped {@link
 * io.github.protasm.lpc2j.efun.EfunRegistry} for lookups at runtime. Efuns provide names, typed
 * signatures, and invocation behavior used by generated bytecode.</p>
 *
 * <p>Assumes concrete implementations are supplied elsewhere (e.g., console efuns) and registered
 * with a {@link io.github.protasm.lpc2j.runtime.RuntimeContext} before compiled code executes. The
 * registry enforces arity and rejects ambiguous overloads.</p>
 */
package io.github.protasm.lpc2j.efun;
