/**
 * Host-facing execution runtime that owns classloading and runtime context lifecycles.
 *
 * <p>This package is intentionally separate from {@code io.github.protasm.lpc2j.runtime}, which
 * contains the language runtime helpers used by generated bytecode.</p>
 */
package io.github.protasm.lpc2j.exec;
